---
version: '3'

services:

  redis:
    image: "redis:latest"

  rediscommander:
    container_name: rediscommander
    hostname: rediscommander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8082:8081"

  tito_hook:
    image: node:12-alpine
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    working_dir: /usr/src/app
    command: ["npx", "nodemon", "index.js"]
    env_file:
      - .env
    environment:
      - PORT=8080
      - NODE_ENV=development
      - REDIS_URL=redis